# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  validate-templates:
    uses: QubitPi/hashicorp-aws/.github/workflows/screwdriver-cd-templates-ci-cd.yml@master

  validate-pipeline:
    name: Validating screwdriver.yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Validate screwdriver.yaml
        uses: satackey/action-js-inline@v0.0.2
        with:
          required-packages: js-yaml screwdriver-data-schema
          script: |
            const error = require("screwdriver-data-schema").api.validator.input
              .validate(
                require('js-yaml').load(
                  'yaml: require("fs").readFileSync("screwdriver.yaml")'
                )
            ).error
            if (error) {
              require('@actions/core').setFailed(error);
            }
